var new_lang = {
    lt1: 'Pedir una llamada gratuita',
    lt2: 'El poder de «Tinedol»',
    lt3: 'La eficiencia',
    lt4: 'Comentarios',
    lt5: '¡Un medio fácil para eliminar hongos, picazón y grietas!',
    lt6: 'Cura el hongo de las uñas y el pie de atleta',
    lt7: 'Elimina la picazón y la peladura',
    lt8: 'Elimina la transpiración y el mal olor',
    lt9: 'Sana las grietas en talones',
    lt10: 'DESCUENTO',
    lt11: '-50%',
    lt12: ' ¡colección limitada!<br> ¡Prisa!<br> ¡Solo <span class="product-how-much"><span class="lastpack">5</span> unidades</span> <br>con el precio especial!',
    lt13: 'La oferta termina dentro de:',
    lt14: '00',
    lt15: 'Horas',
    lt16: '25',
    lt17: 'Minutos',
    lt18: '59',
    lt19: 'Segundos',
    lt20: 'El precio:',
    lt21: 'El precio con el descuento',
    lt22: 'Pedir',
    lt23: 'Sus datos están protegidos',
    lt24: '<span class="title2-span1">¿Piensa que no hay riesgos del hongo? </span> Si ve al menos un síntoma <br> empiece el tratamiento ahora mismo</br>',
    lt25: 'Mal olor',
    lt26: 'Grietas y peladuras',
    lt27: 'Forma anormal de las uñas',
    lt28: 'Uña se pone <br> marrón o amarilla',
    lt29: 'Estrías y manchas <br>blancas en las uñas',
    lt30: 'Picazón y quemazón',
    lt31: 'Ampollas en las pies',
    lt32: 'Entumecimiento y hormigueo',
    lt33: 'Manchas locales <br> en la piel',
    lt34: '¿Qué pasará si no se cura el hongo?',
    lt35: 'Según las estadísticas, uno de cada cinco en España tiene la enfermedad de hongos. <br> Zapato estrecho, calcetines de fibra sintética, saunas, piscinas. <br> <span class="stage__span1"> También parques y playas donde en verano la gente pasea sin zapatos. <br> ¡Todo eso causa las enfermedades horribles!',
    lt36: '1ª fase:',
    lt37: '<i></i>Peladura',
    lt38: '<i></i>Picazón',
    lt39: '<i></i>Transpiración',
    lt40: '<i></i>Mal olor',
    lt41: '<i></i>Incomodidad',
    lt42: '2 fase:',
    lt43: '<i></i>Hongo de uñas',
    lt44: '<i></i>Grietas',
    lt45: '<i></i>Transpiración picazón',
    lt46: '<i></i>Hedor',
    lt47: '<i></i>Uñas débiles y amarillas',
    lt48: '<i></i>Piel “muerta”',
    lt49: '<i></i>Incomodidad <br> cuando camina',
    lt50: '3ª fase:',
    lt51: '<i></i>Peladura y picazón <br> entre los dedos',
    lt52: '<i></i>Úlceras y grietas <br>graves',
    lt53: '<i></i>Dolor',
    lt54: '<i></i>Pus',
    lt55: '<i></i>Pérdida de uñas',
    lt56: '<span class="stage__main-block-span"> ¡Si no cura los pies se puede iniciar una enfermedad muy seria! </span><br> ¡Imagínese que son sus pies! ¿Quiere tener pies así? <br> ¡Diga no!',
    lt57: '¿Cómo funciona <span class="title4-span1">la crema «Tinedol»?</span>',
    lt58: '<span class="work__span1"> «Tinedol» elimina varios problemas a la vez.</span> Sus componentes los eliminan efectivamente',
    lt59: 'Hongo',
    lt60: 'Mal olor',
    lt61: 'Transpiración',
    lt62: 'Grietas',
    lt63: '<span class="consist__text--b">Climbazole</span> pone fin al desarrollo de hongos. Elimina la picazón.',
    lt64: '<span class="consist__text--b">Farnesol</span> desinfecta el organismo y aromatiza. <span class="consist__text--b"> Propóleos</span> tiene propiedades antibacteriales muy fuertes. <span class="consist__text--b">Aceite de árbol de té </span> se mete bajo su piel curando las zonas de problema y elimina el mal olor después de duro día de trabajo.',
    lt65: 'La crema tonifica y humecta su piel de pies.',
    lt66: 'En contraste con otros remedios, la crema Tinedol se absorbe rápidamente y no deja huellas en la ropa y la de cama.',
    lt67: 'Hemos añadido el aceite de piedra a la edición limitada. Lucha efectivamente contra callos. Le hace sentir cómodo y seguro.',
    lt68: '¡Un método fácil para curar <br> hongo, picazón y grietas!',
    lt69: 'Efecto después de 30 días <span class="title6-span1">de uso de</span> «Tinedol»',
    lt70: 'Se elimina el hongo de<br>uñas y pies',
    lt71: 'Rellena el formulario',
    lt72: 'Se va picazón y <br>peladura',
    lt73: 'Olor dulce',
    lt74: 'Pies no sudan',
    lt75: 'Grietas <br> se curan',
    lt76: 'Vigor y comodidad',
    lt77: 'Pies <br>bien cuidados',
    lt78: '¿Cómo usar <span class="title7-span1">la crema «Tinedol»?</span>',
    lt79: 'Antes de usarla lávese los pies con jabón. Aplíquese la crema. Cada noche antes de dormir durante 30 días. <br> ¡Verá que sus talones se ponen más rojas y la piel más sana!',
    lt80: '¿Por qué «Tinedol» es mejor que otros medicamentos?',
    lt81: 'Hay dos tipos de medicamentos: los que no curan y los que funcionan solo al usarlos. La gente que tiene hongos tiene que usar las cremas y ungüentos.',
    lt82: '«Tinedol» cambia toda la situación. Varias investigaciones médicas han mostrado que este medicamento lucha contra los hongos con eficiencia. Ya después de un curso completo el hongo se va para siempre. Este efecto es logrado gracias a los componentes e ingredientes naturales.',
    lt83: 'Opinión de experto',
    lt84: 'Este medicamento ha demostrado su eficiencia. Su ventaja principal es la atención integrada. Aunque no tiene Ud. todos los síntomas es mejor empezar usar Tinedol para la prevención. ¡El hongo se desarrolla muy rápido! Hoy tienes algunos síntomas, pero mañana vas a estar en el hospital tomando antibióticos 5 veces cada día. Cura el hongo ahora mismo. ¡Además, el hongo se puede pasar a cualquier persona de tu familia!',
    lt85: '— Vicente Reguera<br> dermatólogo.',
    lt86: 'Comentarios',
    lt87: 'Antes de empezar a usar Tinedol pensaba que el hongo se desaparece y se aparece… Tomé muchos medicamentos. Los síntomas se iban, pero el hongo no. Fui al hospital y el doctor me recomendó que comprara Tinedol. No tengo ningún problema desde hace 6 meses. <br> ¡Gracias!',
    lt88: 'Carla, Barcelona',
    lt89: ' ¡Talones de un bebé! Nado en la piscina publica cada día y no me sorprendió el hecho que tenía hongos. Porque tenemos duchas y vestuarios comunes. ¿Qué hacer? ¡Todas las chicas de la piscina saben que el remedio ideal es Tinedol!',
    lt90: 'Andrea, Valladolid',
    lt91: 'El hongo empieza a volverse inmune contra los medicamentos. Los pies de mi esposo sudaban mucho y por eso el hongo no se iba. Ya que Tinedol tiene dos funciones importantes (anti-transpiración y anti-hongo) decidimos elegirlo. Hace 3 meses. ¡Ahora todo está bien!',
    lt92: 'Pilar, Valencia',
    lt93: 'BERNADATTE LTD, Av Ricardo J. Alfaro, Panama International       <br>       <a href="http://leadbit.com" target="_blank">Leadbit</a> | <a href="/cdn/files/Privacy Policy.html" target="_blank">Privacy Policy</a> | <a href="http://feedback-team.com" target="_blank">Report</a>',
    title2: 'Comprar «Tinedol». Precios, Comentarios. ¡Pida «Tinedol» ahora!',
};

function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
};